# Comparison of all statistical models for predicting N<sub>2</sub>O and CH<sub>4</sub> flux over Ränskälänkorpi clearcut in 2022

Models are

**Simple model**
$$
\ln{F_{i,k}} = \alpha_k + \beta_k \frac{T_i - 10^{\circ} \text{C}}{10^{\circ} \text{C}} \\
i = 1 \ldots \text{\# observations} \\
k \in \left[  \mathrm{N_2O} ; \mathrm{CH_4} \right] \\
T_i = \text{ Observed air temperature (K)}
$$

**Simple model with soil moisture**
$$
\ln{F_{i,k}} = \alpha_k + \beta_k \frac{T_i - 10^{\circ} \text{C}}{10^{\circ} \text{C}} + \zeta \theta \\
$$
**Full model**
$$
\ln{F_{i,k}} = \alpha_k + \beta_k f(T_{i}) + \sum_{j=1}^{N} \gamma_{j,k}x_{i,j} + \delta_{j,k} x_{i,j} f(T_{i}) \\

f(T_{i}) = \frac{T_i - 10^{\circ} \text{C}}{10^{\circ} \text{C}}
$$

**Full model without ST specific T dependency**
$$
\ln{F_{i,k}} = \alpha_k + \beta_k f(T_{i}) + \sum_{j=1}^{N} \gamma_{j,k}x_{i,j}\\
$$

**Full model with soil moisture**
$$
\ln{F_{i,k}} = \alpha_k + \beta_k f(T_{i}) +\zeta \theta + \sum_{j=1}^{N} \gamma_{j,k}x_{i,j} + \delta_{j,k} x_{i,j} f(T_{i}) \\
$$

**Full model with soil moisture and without ST specific dependency**
$$
\ln{F_{i,k}} = \alpha_k + \beta_k f(T_{i}) +\zeta \theta + \sum_{j=1}^{N} \gamma_{j,k}x_{i,j} \\
$$

Full models are run with 9, 6, 5, 4 and 3 surface types and labelled with "ST9/6/5/4/3" correspondingly

In [ ]:
import pandas as pd
from dotenv import load_dotenv; load_dotenv()

import cloudpickle

import pymc as pm
import arviz as az

%matplotlib widget
%load_ext autoreload
%autoreload 2

WARNING (pytensor.tensor.blas): Using NumPy C-API based implementation for BLAS functions.

# N<sub>2</sub>O

## Load models

In [ ]:
## Simple models
with open('models/simple_model_n2o_revision_mutable.pkl', 'rb') as buff:
    simple_n2o = cloudpickle.load(buff)

with open('models/simple_model_n2o_wtd_mutable.pkl', 'rb') as buff:
    simple_n2o_wtd = cloudpickle.load(buff)

with open('models/simple_model_n2o_theta_mutable.pkl', 'rb') as buff:
    simple_n2o_theta = cloudpickle.load(buff)

## Full models
with open('models/full_model_n2o_st3_revision_mutable.pkl','rb') as buff:
    full_n2o_st3 = cloudpickle.load(buff)

with open('models/full_model_n2o_st4_revision_mutable.pkl','rb') as buff:
    full_n2o_st4 = cloudpickle.load(buff)

with open('models/full_model_n2o_st5_revision_mutable.pkl','rb') as buff:
    full_n2o_st5 = cloudpickle.load(buff)

with open('models/full_model_n2o_st6_revision_mutable.pkl','rb') as buff:
    full_n2o_st6 = cloudpickle.load(buff)

with open('models/full_model_n2o_st9_revision_mutable.pkl','rb') as buff:
    full_n2o_st9 = cloudpickle.load(buff)

## Full models no ST T
with open('models/full_model_n2o_st3_no_ST_T_mutable.pkl','rb') as buff:
    full_n2o_st3_no_st_t = cloudpickle.load(buff)

with open('models/full_model_n2o_st4_no_ST_T_mutable.pkl','rb') as buff:
    full_n2o_st4_no_st_t = cloudpickle.load(buff)

with open('models/full_model_n2o_st5_no_ST_T_mutable.pkl','rb') as buff:
    full_n2o_st5_no_st_t = cloudpickle.load(buff)

with open('models/full_model_n2o_st6_no_ST_T_mutable.pkl','rb') as buff:
    full_n2o_st6_no_st_t = cloudpickle.load(buff)

with open('models/full_model_n2o_st9_no_ST_T_mutable.pkl','rb') as buff:
    full_n2o_st9_no_st_t = cloudpickle.load(buff)

## Full models theta
with open('models/full_model_n2o_st3_theta_mutable.pkl','rb') as buff:
    full_n2o_st3_theta = cloudpickle.load(buff)

with open('models/full_model_n2o_st4_theta_mutable.pkl','rb') as buff:
    full_n2o_st4_theta = cloudpickle.load(buff)

with open('models/full_model_n2o_st5_theta_mutable.pkl','rb') as buff:
    full_n2o_st5_theta = cloudpickle.load(buff)

with open('models/full_model_n2o_st6_theta_mutable.pkl','rb') as buff:
    full_n2o_st6_theta = cloudpickle.load(buff)

with open('models/full_model_n2o_st9_theta_mutable.pkl','rb') as buff:
    full_n2o_st9_theta = cloudpickle.load(buff)

## Full models theta no ST T
with open('models/full_model_n2o_st3_no_ST_T_theta_mutable.pkl','rb') as buff:
    full_n2o_st3_theta_no_st_t = cloudpickle.load(buff)

with open('models/full_model_n2o_st4_no_ST_T_theta_mutable.pkl','rb') as buff:
    full_n2o_st4_theta_no_st_t = cloudpickle.load(buff)

with open('models/full_model_n2o_st5_no_ST_T_theta_mutable.pkl','rb') as buff:
    full_n2o_st5_theta_no_st_t = cloudpickle.load(buff)

with open('models/full_model_n2o_st6_no_ST_T_theta_mutable.pkl','rb') as buff:
    full_n2o_st6_theta_no_st_t = cloudpickle.load(buff)

with open('models/full_model_n2o_st9_no_ST_T_theta_mutable.pkl','rb') as buff:
    full_n2o_st9_theta_no_st_t = cloudpickle.load(buff)

## Put all models to list

In [ ]:
models_n2o = [simple_n2o, simple_n2o_wtd, simple_n2o_theta,
              full_n2o_st3, full_n2o_st4, full_n2o_st5, full_n2o_st6, full_n2o_st9, 
              full_n2o_st3_no_st_t, full_n2o_st4_no_st_t, full_n2o_st5_no_st_t, full_n2o_st6_no_st_t, full_n2o_st9_no_st_t, 
              full_n2o_st3_theta, full_n2o_st4_theta, full_n2o_st5_theta, full_n2o_st6_theta, full_n2o_st9_theta,
              full_n2o_st3_theta_no_st_t, full_n2o_st4_theta_no_st_t, full_n2o_st5_theta_no_st_t, full_n2o_st6_theta_no_st_t, full_n2o_st9_theta_no_st_t]
model_names = ["Simple", "Simple WTD", "Simple theta",
               "Full ST3", "Full ST4", "Full ST5", "Full ST6", "Full ST9",
               "Full ST3 no ST T", "Full ST4 no ST T", "Full ST5 no ST T", "Full ST6 no ST T", "Full ST9 no ST T",
               "Full ST3 theta", "Full ST4 theta", "Full ST5 theta", "Full ST6 theta", "Full ST9 theta",
               "Full ST3 theta no ST T", "Full ST4 theta no ST T", "Full ST5 theta no ST T", "Full ST6 theta no ST T", "Full ST9 theta no ST T",]

## Compute log-likelihood

In [ ]:
for i,model in enumerate(models_n2o):
    print(model_names[i])
    with model["model"]:
        pm.compute_log_likelihood(model["model_res"])

Simple

Simple WTD

Simple theta

Full ST3

Full ST4

Full ST5

Full ST6

Full ST9

Full ST3 no ST T

Full ST4 no ST T

Full ST5 no ST T

Full ST6 no ST T

Full ST9 no ST T

Full ST3 WTD

Full ST4 WTD

Full ST5 WTD

Full ST6 WTD

Full ST9 WTD

Full ST3 WTD no ST T

Full ST4 WTD no ST T

Full ST5 WTD no ST T

Full ST6 WTD no ST T

Full ST9 WTD no ST T

Full ST3 theta

Full ST4 theta

Full ST5 theta

Full ST6 theta

Full ST9 theta

Full ST3 theta no ST T

Full ST4 theta no ST T

Full ST5 theta no ST T

Full ST6 theta no ST T

Full ST9 theta no ST T

## Create dictionary of model traces

In [6]:
traces = [model['model_res'] for model in models_n2o]
models_dict = {model_name: trace for (model_name, trace) in zip(model_names, traces)}

In [7]:
df_comp_loo = az.compare(models_dict)
df_comp_loo

/Users/opa/Ranskalankorpi_CC_EC/.venv/lib/python3.11/site-packages/arviz/stats/stats.py:309: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'False' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df_comp.loc[val] = (
/Users/opa/Ranskalankorpi_CC_EC/.venv/lib/python3.11/site-packages/arviz/stats/stats.py:309: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'log' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df_comp.loc[val] = (

,rank,elpd_loo,p_loo,elpd_diff,weight,se,dse,warning,scale
Full ST9 theta,0,-2452.549708,12.059575,0.000000,0.000005,83.104959,0.000000,False,log
Full ST9 theta no ST T,1,-2459.837912,10.924742,7.288204,0.000005,83.242317,1.795904,False,log
Full ST9 WTD,2,-2465.582619,12.226432,13.032911,0.999892,85.160350,7.977741,False,log
Full ST9 WTD no ST T,3,-2471.744986,10.912246,19.195278,0.000005,85.325934,8.117799,False,log
Full ST6 theta,4,-2528.730096,10.536571,76.180387,0.000004,80.401094,9.333216,False,log
Full ST6 WTD,5,-2536.998197,10.943861,84.448488,0.000005,82.366557,11.272612,False,log
Full ST5 theta,6,-2537.323201,10.079347,84.773493,0.000004,80.480257,9.770455,False,log
Full ST6 theta no ST T,7,-2537.808520,9.719043,85.258812,0.000004,80.598959,9.490354,False,log
Full ST6 WTD no ST T,8,-2545.270742,9.783538,92.721034,0.000005,82.631027,11.345344,False,log
Full ST5 theta no ST T,9,-2545.533083,9.209256,92.983375,0.000004,80.630663,9.905166,False,log
Full ST5 WTD,10,-2548.276004,10.358808,95.726296,0.000004,82.400975,11.592400,False,log
Full ST5 WTD no ST T,11,-2554.696100,9.365094,102.146392,0.000004,82.598281,11.683771,False,log
Full ST9,12,-2702.259249,10.921611,249.709541,0.000004,77.084596,18.763523,False,log
Full ST9 no ST T,13,-2717.799015,9.865245,265.249307,0.000004,77.101423,18.577894,False,log
Full ST6,14,-2751.265509,9.634039,298.715801,0.000004,75.459570,20.927646,False,log
Full ST5,15,-2759.231276,9.115898,306.681568,0.000003,75.488933,20.978987,False,log
Full ST6 no ST T,16,-2768.284456,8.677008,315.734747,0.000003,75.502422,20.719707,False,log
Full ST5 no ST T,17,-2775.203938,8.373229,322.654230,0.000003,75.487985,20.791533,False,log
Full ST4 WTD,18,-2900.728071,8.759543,448.178363,0.000003,74.401792,28.636191,False,log
Full ST4 WTD no ST T,19,-2905.487389,7.787736,452.937681,0.000003,74.629750,28.506602,False,log
Full ST4 theta,20,-2906.220299,8.420940,453.670591,0.000003,72.990038,29.717117,False,log
Full ST4 theta no ST T,21,-2912.985819,7.710154,460.436111,0.000003,73.238548,29.659923,False,log
Full ST3 WTD,22,-2914.057712,8.175848,461.508003,0.000003,74.340853,28.877672,False,log
Full ST3 theta,23,-2917.525248,8.017014,464.975540,0.000003,72.964346,29.917725,False,log
Full ST3 WTD no ST T,24,-2918.575171,7.474918,466.025463,0.000003,74.594139,28.777868,False,log
Full ST3 theta no ST T,25,-2923.945971,7.313661,471.396263,0.000003,73.250716,29.894495,False,log
Full ST4,26,-3056.235760,7.616419,603.686052,0.000002,69.954103,33.342818,False,log
Full ST3,27,-3062.846426,7.191338,610.296717,0.000002,69.951149,33.417209,False,log
Full ST4 no ST T,28,-3068.731611,6.834741,616.181903,0.000002,70.022886,33.129309,False,log
Full ST3 no ST T,29,-3075.075194,6.467256,622.525486,0.000002,70.069106,33.214844,False,log
Simple WTD,30,-3702.425588,3.952297,1249.875879,0.000002,59.437801,52.338002,False,log
Simple theta,31,-3714.639006,3.971252,1262.089298,0.000002,58.970171,53.129814,False,log
Simple,32,-3751.555517,3.269500,1299.005809,0.000000,59.272983,53.826178,False,log

# CH<sub>4</sub>

## Load models

In [ ]:
## Simple models
with open('models/simple_model_ch4_revision_mutable.pkl', 'rb') as buff:
    simple_ch4 = cloudpickle.load(buff)

with open('models/simple_model_ch4_wtd_mutable.pkl', 'rb') as buff:
    simple_ch4_wtd = cloudpickle.load(buff)

with open('models/simple_model_ch4_theta_mutable.pkl', 'rb') as buff:
    simple_ch4_theta = cloudpickle.load(buff)

## Full models
with open('models/full_model_ch4_st3_revision_mutable.pkl','rb') as buff:
    full_ch4_st3 = cloudpickle.load(buff)

with open('models/full_model_ch4_st4_revision_mutable.pkl','rb') as buff:
    full_ch4_st4 = cloudpickle.load(buff)

with open('models/full_model_ch4_st5_revision_mutable.pkl','rb') as buff:
    full_ch4_st5 = cloudpickle.load(buff)

with open('models/full_model_ch4_st6_revision_mutable.pkl','rb') as buff:
    full_ch4_st6 = cloudpickle.load(buff)

with open('models/full_model_ch4_st9_revision_mutable.pkl','rb') as buff:
    full_ch4_st9 = cloudpickle.load(buff)

## Full models no ST T
with open('models/full_model_ch4_st3_no_ST_T_mutable.pkl','rb') as buff:
    full_ch4_st3_no_st_t = cloudpickle.load(buff)

with open('models/full_model_ch4_st4_no_ST_T_mutable.pkl','rb') as buff:
    full_ch4_st4_no_st_t = cloudpickle.load(buff)

with open('models/full_model_ch4_st5_no_ST_T_mutable.pkl','rb') as buff:
    full_ch4_st5_no_st_t = cloudpickle.load(buff)

with open('models/full_model_ch4_st6_no_ST_T_mutable.pkl','rb') as buff:
    full_ch4_st6_no_st_t = cloudpickle.load(buff)

with open('models/full_model_ch4_st9_no_ST_T_mutable.pkl','rb') as buff:
    full_ch4_st9_no_st_t = cloudpickle.load(buff)

## Full models theta
with open('models/full_model_ch4_st3_theta_mutable.pkl','rb') as buff:
    full_ch4_st3_theta = cloudpickle.load(buff)

with open('models/full_model_ch4_st4_theta_mutable.pkl','rb') as buff:
    full_ch4_st4_theta = cloudpickle.load(buff)

with open('models/full_model_ch4_st5_theta_mutable.pkl','rb') as buff:
    full_ch4_st5_theta = cloudpickle.load(buff)

with open('models/full_model_ch4_st6_theta_mutable.pkl','rb') as buff:
    full_ch4_st6_theta = cloudpickle.load(buff)

with open('models/full_model_ch4_st9_theta_mutable.pkl','rb') as buff:
    full_ch4_st9_theta = cloudpickle.load(buff)

## Full models theta no ST T
with open('models/full_model_ch4_st3_no_ST_T_theta_mutable.pkl','rb') as buff:
    full_ch4_st3_theta_no_st_t = cloudpickle.load(buff)

with open('models/full_model_ch4_st4_no_ST_T_theta_mutable.pkl','rb') as buff:
    full_ch4_st4_theta_no_st_t = cloudpickle.load(buff)

with open('models/full_model_ch4_st5_no_ST_T_theta_mutable.pkl','rb') as buff:
    full_ch4_st5_theta_no_st_t = cloudpickle.load(buff)

with open('models/full_model_ch4_st6_no_ST_T_theta_mutable.pkl','rb') as buff:
    full_ch4_st6_theta_no_st_t = cloudpickle.load(buff)

with open('models/full_model_ch4_st9_no_ST_T_theta_mutable.pkl','rb') as buff:
    full_ch4_st9_theta_no_st_t = cloudpickle.load(buff)

## Put all models to list

In [ ]:
models_ch4 = [simple_ch4, simple_ch4_wtd, simple_ch4_theta,
              full_ch4_st3, full_ch4_st4, full_ch4_st5, full_ch4_st6, full_ch4_st9, 
              full_ch4_st3_no_st_t, full_ch4_st4_no_st_t, full_ch4_st5_no_st_t, full_ch4_st6_no_st_t, full_ch4_st9_no_st_t, 
              full_ch4_st3_theta, full_ch4_st4_theta, full_ch4_st5_theta, full_ch4_st6_theta, full_ch4_st9_theta,
              full_ch4_st3_theta_no_st_t, full_ch4_st4_theta_no_st_t, full_ch4_st5_theta_no_st_t, full_ch4_st6_theta_no_st_t, full_ch4_st9_theta_no_st_t]
model_names = ["Simple", "Simple WTD", "Simple theta",
               "Full ST3", "Full ST4", "Full ST5", "Full ST6", "Full ST9",
               "Full ST3 no ST T", "Full ST4 no ST T", "Full ST5 no ST T", "Full ST6 no ST T", "Full ST9 no ST T",
               "Full ST3 theta", "Full ST4 theta", "Full ST5 theta", "Full ST6 theta", "Full ST9 theta",
               "Full ST3 theta no ST T", "Full ST4 theta no ST T", "Full ST5 theta no ST T", "Full ST6 theta no ST T", "Full ST9 theta no ST T",]

## Compute log-likelihood

In [ ]:
for i,model in enumerate(models_ch4):
    print(model_names[i])
    with model["model"]:
        pm.compute_log_likelihood(model["model_res"])

Simple

Simple WTD

Simple theta

Full ST3

Full ST4

Full ST5

Full ST6

Full ST9

Full ST3 no ST T

Full ST4 no ST T

Full ST5 no ST T

Full ST6 no ST T

Full ST9 no ST T

Full ST3 WTD

Full ST4 WTD

Full ST5 WTD

Full ST6 WTD

Full ST9 WTD

Full ST3 WTD no ST T

Full ST4 WTD no ST T

Full ST5 WTD no ST T

Full ST6 WTD no ST T

Full ST9 WTD no ST T

Full ST3 theta

Full ST4 theta

Full ST5 theta

Full ST6 theta

Full ST9 theta

Full ST3 theta no ST T

Full ST4 theta no ST T

Full ST5 theta no ST T

Full ST6 theta no ST T

Full ST9 theta no ST T

## Create dictionary of model traces

In [6]:
traces = [model['model_res'] for model in models_ch4]
models_dict = {model_name: trace for (model_name, trace) in zip(model_names, traces)}

In [8]:
df_comp_loo = az.compare(models_dict)
df_comp_loo

/Users/opa/Ranskalankorpi_CC_EC/.venv/lib/python3.11/site-packages/arviz/stats/stats.py:309: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'False' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df_comp.loc[val] = (
/Users/opa/Ranskalankorpi_CC_EC/.venv/lib/python3.11/site-packages/arviz/stats/stats.py:309: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'log' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df_comp.loc[val] = (

,rank,elpd_loo,p_loo,elpd_diff,weight,se,dse,warning,scale
Full ST9 theta,0,3529.471192,16.986538,0.000000,9.106844e-01,91.181130,0.000000,False,log
Full ST6 theta,1,3526.323609,13.870357,3.147583,4.422544e-02,91.111496,3.800959,False,log
Full ST5 theta,2,3483.729718,12.638904,45.741475,1.519720e-12,90.398166,7.648765,False,log
Full ST4 theta,3,3468.740600,11.190252,60.730593,5.475913e-06,89.154374,13.911846,False,log
Full ST9 theta no ST T,4,3435.487385,14.571161,93.983808,3.490683e-12,90.026099,8.671319,False,log
Full ST6 theta no ST T,5,3428.643825,12.435349,100.827367,3.842237e-12,89.636760,9.434995,False,log
Full ST3 theta,6,3414.470157,10.029822,115.001035,2.045545e-12,88.389741,16.030301,False,log
Full ST5 theta no ST T,7,3408.437331,11.546562,121.033861,4.382300e-12,89.350543,10.991564,False,log
Full ST4 theta no ST T,8,3374.980246,9.900148,154.490946,4.111793e-12,87.750892,15.999469,False,log
Full ST3 theta no ST T,9,3340.180077,9.089166,189.291115,5.046957e-12,87.325689,17.641034,False,log
Full ST9 WTD,10,3288.072682,15.436074,241.398511,7.986273e-12,83.494842,20.158668,False,log
Full ST6 WTD,11,3285.730365,12.928968,243.740827,7.986246e-12,83.565699,20.455857,False,log
Full ST4 WTD,12,3243.198470,10.372556,286.272723,7.809174e-12,82.293424,24.054386,False,log
Full ST5 WTD,13,3239.885934,12.030682,289.585259,1.004720e-11,82.741288,21.218851,False,log
Simple theta,14,3206.383553,5.976517,323.087639,7.304856e-12,84.904586,23.907939,False,log
Full ST3 WTD,15,3193.186953,9.364803,336.284240,9.610687e-12,81.570043,24.995994,False,log
Full ST9 WTD no ST T,16,3169.772657,13.753341,359.698536,1.250710e-11,81.997060,22.275968,False,log
Full ST6 WTD no ST T,17,3167.450598,11.455710,362.020595,1.256208e-11,81.844268,22.617911,False,log
Full ST5 WTD no ST T,18,3146.610113,10.585371,382.861079,1.326630e-11,81.506732,23.133474,False,log
Full ST4 WTD no ST T,19,3130.990700,9.214863,398.480493,1.226245e-11,80.702216,25.519561,False,log
Full ST3 WTD no ST T,20,3101.979949,8.551351,427.491244,1.286042e-11,80.402895,26.376643,False,log
Simple WTD,21,2991.587545,5.335364,537.883647,1.191619e-11,78.911790,31.013364,False,log
Full ST6,22,2804.452502,11.132693,725.018690,1.068935e-07,74.908370,42.276560,False,log
Full ST9,23,2801.637880,13.850976,727.833312,7.443133e-07,74.798364,42.248876,False,log
Full ST5,24,2772.429422,10.335076,757.041770,3.996197e-12,74.382593,42.374996,False,log
Full ST4,25,2771.407041,8.931620,758.064152,1.223868e-12,73.850245,43.425002,False,log
Full ST3,26,2748.617118,7.991275,780.854075,2.431860e-10,73.646165,43.472725,False,log
Full ST6 no ST T,27,2703.995687,9.934769,825.475506,5.539556e-12,73.063384,42.559848,False,log
Full ST9 no ST T,28,2702.269280,11.976367,827.201913,5.918423e-12,73.041651,42.487047,False,log
Full ST5 no ST T,29,2691.782164,8.845245,837.689029,6.472105e-12,72.932969,42.676897,False,log
Full ST4 no ST T,30,2677.110553,7.916566,852.360640,2.631401e-07,72.125137,43.556948,False,log
Full ST3 no ST T,31,2668.998496,6.934506,860.472697,3.597940e-07,72.188902,43.670562,False,log
Simple,32,2585.572428,3.905628,943.898764,4.508325e-02,71.514646,46.214130,False,log